#!/usr/bin/sh

sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor HDMI-0 -d I II
bspc monitor DVI-D-0 -d III IV V VI VII

sh ~/.config/polybar/launch.sh	

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Dracula colors 

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

feh --bg-fill /home/jonas/Pictures/daniel-leone-v7daTKlZzaw-unsplash.jpg

killall -9 sxhkd dunst

sxhkd &
dunst &
flameshot &
lxpolkit &
slack &
xsetroot -cursor_name left_ptr &

notify-send "Bspwm Loaded"
